
name: NPM Publish

on:
  workflow_run:
    workflows: [build]
    types:
      - completed
  push:
    branches:
      -master

jobs:
  publish-npm:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Package publish
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
